import '@/app/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/components/Header/index.js';
import { Providers } from '@/components/Providers.js';
import { Footer } from '@/components/Footer/index.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + " relative"}>
                <Providers>
                    <Header />
                    <div className="flex min-h-screen w-full justify-center bg-black">{children}</div>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
